name: Build and Publish
on:
  push:
  release:
    types: [created, edited]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: wget -O $RUNNER_TEMP/jdk.tar.gz https://download.java.net/java/early_access/jextract/22/3/openjdk-22-jextract+3-13_linux-x64_bin.tar.gz
      - run: tar -xf $RUNNER_TEMP/jdk.tar.gz
      - run: echo "JEXTRACT_HOME=$(pwd)/jextract-22" >> $GITHUB_ENV
      - uses: actions/setup-java@v4
        id: install-jdk
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper

      - name: Download natives
        run: ./gradlew -PwgpuVersion='v0.19.1.1' :natives:download

      - name: Extract natives
        run: ./gradlew -PwgpuVersion='v0.19.1.1' :natives:unzip

      - name: Copy headers
        run: ./gradlew -PwgpuVersion='v0.19.1.1' ':natives:copyWgpuHeaders'

      - name: Generate bindings
        run: ./gradlew -PwgpuVersion='v0.19.1.1' -Pjextract.home=${{ env.JEXTRACT_HOME }} :lib:bindings

      - name: Publish bindings
        uses: actions/upload-artifact@v4
        with:
          name: webgpu-bindings
          path: lib/build/webgpu.jar
