name: Build and Publish
on:
  push:
  release:
    types: [created, edited]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir $RUNNER_TEMP/jextract
      - run: wget -O $RUNNER_TEMP/jextract/jdk.tar.gz https://download.java.net/java/early_access/jextract/22/3/openjdk-22-jextract+3-13_linux-x64_bin.tar.gz
      - run: tar -xf $RUNNER_TEMP/jextract/jdk.tar.gz
      - uses: actions/setup-java@v4
        id: install-jdk
        with:
          cache: gradle
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Download natives
        run: ./gradlew -PwgpuVersion='v0.19.1.1' :natives:download

      - name: Extract natives
        run: ./gradlew -PwgpuVersion='v0.19.1.1' :natives:unzip

      - name: Generate bindings
        run: ./gradlew -PwgpuVersion='v0.19.1.1' -Pjextract.home=$RUNNER_TEMP/jextract/jextract-22 :lib:bindings
